[project]
name = "docmesh-kbms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pytest-asyncio>=1.4.0",
]

[tool.setuptools.packages.find]
include = ["kbms*"]
exclude = []

[tool.pytest.ini_options]
testpaths = ["test_kbms"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
markers = []
